[build]
  publish = "src"
  command = ""

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  minify = true

[build.processing.images]
  compress = true
  quality = 85

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' *.google.com *.gstatic.com *.googleapis.com *.formspree.io https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: https://cdn.jsdelivr.net/npm/; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https: *.googleapis.com *.gstatic.com; font-src 'self' https: data:; frame-src 'self' *.google.com;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Cache-Control = "public, max-age=31536000"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.googleapis.com/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/plain"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-lighthouse"